/**
* Blog Types
*/
export const BLOG_LOADING = 'BLOG_LOADING'
export const LOAD_BLOG_POSTS_SUCCESS = 'LOAD_BLOG_POSTS_SUCCESS';
export const POST_SENDING = 'POST_SENDING';
export const POST_SENT_SUCCESSFULLY = 'POST_SENT_SUCCESSFULLY';